theme: jekyll-theme-minimal
title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!

# Google Fonts link for Helvetica Neue
head: |
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Helvetica+Neue&display=swap">
  
# Set default font and style settings
defaults:
  -
    scope:
      path: "" # Apply globally
    values:
      layout: default
      font: "Helvetica Neue"
